// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebzxprieodroyhaidepz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVienhwcmllb2Ryb3loYWlkZXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTM3MTIsImV4cCI6MjA1OTA4OTcxMn0.KDytoS4ucwKR82og4RaEnIMLUxTmFGus_bIcNiOnFzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);